# Generated by Django 4.1.2 on 2022-10-31 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yelp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yelpuser',
            name='elite',
        ),
        migrations.RemoveField(
            model_name='yelpuser',
            name='friends',
        ),
    ]
