# Generated by Django 4.1.2 on 2022-10-31 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yelp', '0002_remove_yelpuser_elite_remove_yelpuser_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='yelpuser',
            name='elite',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='yelpuser',
            name='friends',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
