# Generated by Django 4.1.2 on 2022-11-01 00:32

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yelp', '0004_remove_yelpuser_elite_remove_yelpuser_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='yelpuser',
            name='elite',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(blank=True, null=True), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='yelpuser',
            name='friends',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=22, null=True), blank=True, null=True, size=None),
        ),
    ]
