# Generated by Django 4.1.2 on 2022-11-01 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yelp', '0005_yelpuser_elite_yelpuser_friends'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yelpuser',
            name='elite',
        ),
        migrations.RemoveField(
            model_name='yelpuser',
            name='friends',
        ),
    ]
