# Generated by Django 4.1.2 on 2022-11-01 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yelp', '0006_remove_yelpuser_elite_remove_yelpuser_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='yelpuser',
            name='elite',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='yelpuser',
            name='friends',
            field=models.TextField(blank=True, null=True),
        ),
    ]
