# Generated by Django 4.1.2 on 2022-11-02 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yelp', '0008_alter_review_business_id_alter_review_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='business_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='yelp.business'),
        ),
        migrations.AlterField(
            model_name='review',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='yelp.yelpuser'),
        ),
    ]
